/*
 * generated by Xtext 2.16.0
 */
package xyz.elite.xtext.languages.plantuml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PlantUMLRuntimeModule extends AbstractPlantUMLRuntimeModule {
}
