/*
 * generated by Xtext 2.16.0
 */
package xyz.elite.xtext.languages.plantuml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PlantUMLStandaloneSetup extends PlantUMLStandaloneSetupGenerated {

	def static void doSetup() {
		new PlantUMLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
