/*
 * generated by Xtext 2.16.0
 */
package xyz.elite.xtext.languages.plantuml.ide


/**
 * Use this class to register ide components.
 */
class PlantUMLIdeModule extends AbstractPlantUMLIdeModule {
}
