/*
 * generated by Xtext 2.16.0
 */
package xyz.elite.xtext.languages.plantuml.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class PlantUMLWebModule extends AbstractPlantUMLWebModule {
}
