
@startuml

' Configuration
header All Features PUML Diagram
footer Seite %page%/%lastpage%
skinparam roundcorner 25
title TITEL =)
hide footbox

actor "Alice" << (O, #eeaaaa) >> #aF7

autonumber 3 2
[--> Alice : Externer Trigger
activate Alice

participant "Multiline\nBob" as Bob

autoactivate on
Alice -> Bob : start()

== Initialization ==

/'
Multiline comment:
Syntax bellow yields a 100 pixel high spacing :)
'/
||100||

box "Cloud Services" #8877cc
create control "CCC-Mock"
Bob o-> "CCC-Mock" ++: request(POST, "/event/${location}", [location : "dingolfing"])
... wait(10 s) Auf schönes Wetter ;) ...
end box
return response(200||201, [ event: "42" ])

"CCC-Mock" -> "CCC-Mock" : bootSkynet()

== Hier wirds kritisch ==

Bob<-[#0000aa]->Alice : Comunicación muy importante

ref over Alice, Bob: Hier hängt ein ref Kasten\nmit mehreren Zeilen Text\n

== Schicksalskram ==

alt robot takeover
  Alice -[#ffaaaa]>x "CCC-Mock" !! : Sie wurden soeben terminiert
  destroy "CCC-Mock"
  note left of Alice #eba : Alice ist großer Fan\nder Terminator Filmreihe ;)
else peacful
  loop 100 times
    Alice -> "CCC-Mock" : request(POST, "/gift")
    "CCC-Mock" -> Alice : Thank you =)
  end
end

[<-- Alice : Result 

@enduml