@startuml
participant User

User -> A: DoWork
activate A #FFBBBB

A -> A: Internal call
activate A #adf

A -> B: << createRequest >>
activate B

B --> A: RequestCreated
deactivate B
deactivate A
A -> User: Done
deactivate A

autoactivate on
alice -> bob : hello
bob -> bob : self call
bill -> bob #005500 : hello from thread 2
'bob -> george ** : create
'bob -> george !! : delete

@enduml