/*
 * generated by Xtext 2.16.0
 */
package xyz.elite.xtext.languages.plantuml.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import xyz.elite.xtext.languages.plantuml.plantUML.Model

@RunWith(XtextRunner)
@InjectWith(PlantUMLInjectorProvider)
class PlantUMLParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			SEQUENCE @startuml

			participant "I have a really long\nlong name" as L #99FF99
			participant "Alice" #aF7
			actor FOO

			FOO <- "BAR()" : POST "/lol/xd/${var}" (var : "1")
			... wait(10 d) : Dies ist ein Kommentar ...
			BAR --> FOO : http(200 | 201 | 410) - (res: "42")
			participant "CCC-Mock"

			Alice -> Alice: This is a signal to self.\nIt also demonstrates\nmultiline \ntext
			Bob->Bob : Dies ist eine tolle Nachricht
			Alice<--Alice : Dies ist eine tolle Nachricht

			@enduml
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
