@startuml

Alice -> Bob : request(GET, "age")

alt weather==sunny
	Alice -> Bob : request(GET, "name")
	Bob --> Alice : response(200 ACCEPTED, { name: "Bob" })
	
	Alice -> Bob : request(GET, "mainframe_location")

	CCC -> ECS
	
	alt moon==fullmoon
		return 200
	end

	Bob --> Alice : response(410 GONE)
else weather==Cloudy
	Alice -> Bob : request(GET, "name")
	Bob --> Alice : response(500 DENIED)
else
	Alice -> Bob : request(GET, "type")
	Bob --> Alice : response(418 I_AM_A_TEAPOT)
end

Bob -> Alice : response(404 NOT_FOUND)

@enduml