@startuml

Alice -> Bob : request(GET, "name")

alt weather==sunny
	Bob --> Alice : response(200 ACCEPTED, { name: "Bob" })
	
	CCC -> ECS
	alt moon==fullmoon
		return 200
	else
		Bob --> Alice : response(410 GONE)
	end
else name==Hans
	Bob --> Alice : response(500 DENIED)
'else
'	Bob --> Alice : response(418 I_AM_A_TEAPOT)
end

Bob -> Alice : response(404 NOT_FOUND)

@enduml