@startuml

Alice -> Bob : request(GET, "name")

alt weather==sunny
	Bob --> Alice : response(200 ACCEPTED, { name: "Bob" })
	
	Alice -> Bob : request(GET, "social_security_number")

	CCC -> ECS : request(POST, "/event/create/{id}", { id: 42 })
	
	alt moon==fullmoon
		return 200
	end

	Bob --> Alice : response(400 ACCESS_FORBIDDEN)
else weather==Cloudy
	Bob --> Alice : response(500 ERROR)
else
	Bob --> Alice : response(418 I_AM_A_TEAPOT)
end

Alice -> Bob : request(GET, "age")
Bob -> Alice : response(404 NOT_FOUND)

@enduml