SEQUENCE @startuml

PARTICIPANT A
PARTICIPANT B
PARTICIPANT C

activate B
B -> C : GET "/b2c"
activate C
C -> B : 200
deactivate C
B -> A : GET "/b2a"
activate A
A -> B : 200
deactivate B
A -> C : GET "/a2c"
activate C
C -> A : 200
deactivate C
deactivate A

@enduml
