@startasyncconfig
async[1] = Owner request(GET, "/isplanted/${plantname}") response(200, {success: true}) ' timeout(10s, 1s)
@endasyncconfig

@startvariant
plantname="strelitzie"

' Path setup
Owner.path="/owner"
Gardener.path="/gardener"
Garden.path="/garden"
PflanzenKoelle.path="/pflanzenshop"
@endvariant

@startvariant
plantname="cactus"

' Path setup
Owner.path="/owner"
Gardener.path="/gardener"
Garden.path="/garden"
PflanzenKoelle.path="/pflanzenshop"
@endvariant

@startuml

activate Owner

"Owner" -[#green]> Gardener : async[1] request(POST, "/doplant/${plantname}")
activate Gardener
Gardener -[#green]-> "Owner" : response(200)

alt "0"==0
	note over Gardener : Nur bei schönem Wetter pflanzt\nder Gärtner Pflanzen
	Gardener -[#green]> Garden : request(GET, "/plant/exists/${plantname}")
	activate Garden

	alt []=="0"
	    Garden --> Gardener : response(200, { exists: true })
	else
	    Garden --> Gardener : response(200, { exists: false })
	end
	deactivate Garden

    autoactivate on

    alt !${exists}
	    Gardener-[#green]> PflanzenKoelle: request(GET, "/buy/${plantname}")
	    return response(200, {plant: "OaPflonzn"})
	
	    Gardener-[#green]> Garden : request(POST, "/plant/${plant}")
	    return response(200)
	end

    ... wait(10s) ...
    autoactivate off
    Gardener -[#green]> "Owner" : async[1] request(POST, "/planted-status", {success: true})
else
	note over Gardener : Zurücklehnen und auf Sonne warten
	... wait(1s) ...
	Gardener -[#green]> "Owner" : async[1] request(POST, "/planted-status", {success: false})
end

deactivate Gardener
deactivate Owner

@enduml