@startasyncconfig
async[1] = Owner request(GET, "planted/${plantname}") response(200, {success: true}) ' timeout(10s, 1s)
@endasyncconfig

@startvariant
plantname="Strelitzie"
@endvariant

@startvariant
plantname="Cactus"
@endvariant

@startuml

activate Owner

"Owner" -[#green]> Gardener : async[1] request(POST, "task/plant/${plantname}")
activate Gardener
Gardener -[#green]-> "Owner" : response(200)

alt weather=="sunny"
	note over Gardener : Nur bei schönem Wetter pflanzt\nder Gärtner Pflanzen
	Gardener -[#green]> Garden : request(GET, "plants/all/${plantname}")
	activate Garden

	alt garden.hasPlant(${plantname})
	    Garden --> Gardener : response(200, { plantexists: true })
	else
	    Garden --> Gardener : response(200, { plantexists: false })
	end
	deactivate Garden

    autoactivate on

    alt ${plantexists}
	    Gardener-[#green]> PflanzenKoelle: request(GET, "plants/${plantname}")
	    return response(200, {plant: "Oa Pflonzn"})
	
	    Gardener-[#green]> Garden : request(POST, "plant/${plant}")
	    return response(200)
	end

    ... wait(10s) ...
    autoactivate off
    Gardener --> "Owner" : async[1] request(POST, "planted/success", {plantname: "${plantname}"})
else weather=="cloudy"
	note over Gardener : Zurücklehnen und auf Sonne warten
	... wait(1s) ...
	Gardener --> "Owner" : async[1] request(POST, "planted/failure", {plantname: "${plantname}"})
end 

deactivate Gardener
deactivate Owner

@enduml