SEQUENCE @startuml

PARTICIPANT CCCMock
PARTICIPANT XCS
PARTICIPANT Tester
PARTICIPANT SVDS

CCCMock -> SVDS : GET "svds/vehicle/internal/v2/${vin}"
activate SVDS
SVDS --> CCCMock : 200 - (marketRegion : "1")
deactivate SVDS

Tester -> XCS : GET "xcs/vin/v1/${vin}"
activate XCS
XCS --> Tester : 200
deactivate XCS

Tester -> CCCMock : GET "event/${eventid}"
activate CCCMock
CCCMock --> Tester : 200 - (eventData : "1")
deactivate CCCMock

XCS -> SVDS : GET "test"
activate XCS
SVDS --> XCS : 200
deactivate XCS

@enduml
