@startuml

PARTICIPANT Tester
PARTICIPANT CCCMock
PARTICIPANT XCS
PARTICIPANT SVDS

Tester -> SVDS : request(GET, "svds/vehicle/internal/v2/${vin}")
activate SVDS
SVDS --> Tester : response(200, {marketRegion: "1"})
deactivate SVDS

Tester -> XCS : request(GET, "xcs/vin/v1/${vin}")
activate XCS
XCS --> Tester : response(200)
deactivate XCS

... wait(2s) due to background processing...

Tester -> CCCMock : request(GET, "event/${eventid}")
activate CCCMock
CCCMock --> Tester : response(200, {eventData: "1" })
deactivate CCCMock


@enduml
