@startvariant
id="123"
eventId="645"
vin="987"
@endvariant

@startuml

participant "Voicemanager" as VM
participant XCS
participant DataService
participant CRS
participant EventNotifier
participant ELOS
participant CCC

autoactivate on

XCS -> DataService : request(GET,  "/vehicle/internal/${vin}")
return response(200, {homeCountry : "/homeCountry", positionCountry : "/positionCountry", brand : "/brand"})

XCS -> CRS : request(POST, "routingTargets/find", {eventId : "${eventId}", serviceType : "${serviceType}", vin : "${vin}", homeCountry : "${homeCountry}", positionCountry : "${positionCountry}", brand : "${brand}"})
return response(200, {voiceTargets : "/voiceTargets"})

alt "${xcsServiceType} == 'ACall'"
	XCS -> EventNotifier : request(PUT, "xcs/notify/${eventId}", {homeCountry : "${homeCountry}", positionCountry : "${positionCountry}", brand : "${brand}"})
	return response(200)
end

alt "${xcsServiceType} == 'BCall'"
	XCS -> ELOS : request(PUT, "xcs/notify/${eventId}", {homeCountry : "${homeCountry}", positionCountry : "${positionCountry}", brand : "${brand}"})
	return response(200)
end

XCS -> CCC : request(POST, "xcs/eventReceived", {eventId : "${eventId}", serviceType : "${serviceType}", homeCountry : "${homeCountry}", positionCountry : "${positionCountry}", brand : "${brand}"})
return response(200)

XCS -> VM : request(POST, "/setupCall", {eventId : "${eventId}", vin : "${vin}", voiceTargets : "${voiceTargets}"})
return response(200)

@enduml
